services:
  - type: web
    name: your-app-name
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: FLASK_ENV
        value: production
